# cloudbuild.yaml

steps:
# Build and push backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/validatus-backend:latest', '-f', './backend/Dockerfile.gcp', './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/validatus-backend:latest']

# Build and push frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/validatus-frontend:latest', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/validatus-frontend:latest']

# Deploy backend to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - validatus-backend
  - --image
  - gcr.io/$PROJECT_ID/validatus-backend:latest
  - --region
  - us-central1
  - --platform
  - managed
  - --memory
  - 2Gi
  - --cpu
  - '2'
  - --concurrency
  - '100'
  - --max-instances
  - '10'
  - --timeout
  - '900'
  - --set-env-vars
  - PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production,GCLOUD_PROJECT=$PROJECT_ID,LOCAL_DEVELOPMENT_MODE=false
  - --allow-unauthenticated
  - --port=8000

# Deploy frontend to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - validatus-frontend
  - --image
  - gcr.io/$PROJECT_ID/validatus-frontend:latest
  - --region
  - us-central1
  - --platform
  - managed
  - --memory
  - 512Mi
  - --cpu
  - '1'
  - --concurrency
  - '1000'
  - --max-instances
  - '5'
  - --timeout
  - '300'
  - --port=80
  - --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/validatus-backend:latest'
- 'gcr.io/$PROJECT_ID/validatus-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY