steps:
  # Build frontend with HTTPS backend URL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'frontend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/validatus-frontend:https-secure'
      - '--build-arg'
      - 'VITE_API_URL=https://validatus-backend-ssivkqhvhq-uc.a.run.app'
      - 'frontend'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-frontend:https-secure']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'validatus-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/validatus-frontend:https-secure'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_API_URL=https://validatus-backend-ssivkqhvhq-uc.a.run.app,REACT_APP_API_BASE_URL=https://validatus-backend-ssivkqhvhq-uc.a.run.app'

timeout: '1200s'
