steps:
  # Build optimized Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/validatus-backend:latest'
      - 'backend/'
    timeout: '1800s'  # 30 minutes

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-backend:latest']

  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/validatus-frontend:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-frontend:latest']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'validatus-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production,GCLOUD_PROJECT=$PROJECT_ID,LOCAL_DEVELOPMENT_MODE=false'
      - '--port=8000'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'validatus-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/validatus-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--port=80'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/validatus-backend:latest'
  - 'gcr.io/$PROJECT_ID/validatus-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'  # More CPU for faster builds
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'  # 1 hour total timeout
