steps:
  # NOTE: Backend should be deployed using backend/cloudbuild.yaml
  # which has proper Cloud SQL configuration. This file only deploys frontend.
  
  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/validatus-frontend:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-frontend:latest']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'validatus-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/validatus-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--port=80'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/validatus-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'  # More CPU for faster builds
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'  # 1 hour total timeout
