steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'backend/Dockerfile.gcp',
      '-t', 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/validatus-backend:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/validatus-backend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'validatus-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production,CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:us-central1:validatus-primary'
    - '--add-cloudsql-instances'
    - '$PROJECT_ID:us-central1:validatus-primary'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '900'

images:
- 'gcr.io/$PROJECT_ID/validatus-backend:$BUILD_ID'
- 'gcr.io/$PROJECT_ID/validatus-backend:latest'
