# Alert Policy: High Error Rate
# Triggers when error rate exceeds 5% for any endpoint

displayName: "Validatus - High Error Rate"
documentation:
  content: |
    # High Error Rate Alert
    
    This alert triggers when the error rate for any API endpoint exceeds 5%.
    
    ## Threshold
    - **Condition**: Error rate > 5%
    - **Duration**: 5 minutes
    - **Aggregation**: Mean across all instances
    
    ## Actions
    1. Check Cloud Run service logs for errors
    2. Review endpoint-specific error patterns
    3. Verify service health and dependencies
    4. Check for recent deployments or changes
    
    ## Resolution
    - Fix identified issues in the code
    - Scale up service instances if needed
    - Update error handling and retry logic
    - Review and optimize problematic endpoints
  mimeType: "text/markdown"

conditions:
  - displayName: "Error rate condition"
    conditionThreshold:
      filter: |
        resource.type="cloud_run_revision" AND
        resource.labels.service_name="validatus-backend" AND
        metric.type="run.googleapis.com/request_count" AND
        metric.labels.response_code_class!="2xx"
      comparison: "COMPARISON_GREATER_THAN"
      thresholdValue: 0.05
      duration: "300s"
      aggregations:
        - alignmentPeriod: "60s"
          perSeriesAligner: "ALIGN_RATE"
          crossSeriesReducer: "REDUCE_MEAN"
          groupByFields:
            - "metric.labels.route"
            - "metric.labels.method"
      trigger:
        count: 1
      evaluationMissingData: "EVALUATION_MISSING_DATA_NO_OP"

combiner: "OR"
enabled: true

alertStrategy:
  autoClose: "1800s"
  notificationRateLimit:
    period: "3600s"

notificationChannels:
  - "projects/validatus-prod/notificationChannels/email-alerts"
  - "projects/validatus-prod/notificationChannels/slack-alerts"
